### ISSUE TITLE
Bingo stat collection

### ISSUE THREAD

**Issue by simon816** [TCDG/ScammerBingoApp#6]
Hi, have you thought about adding a way to submit a bingo session to some web service so we can collectively see what common things there are etc? I think it would be a cool statistic.

**Comment by afroraydude** [comment]
So you are saying that I should allow people to send what buttons they clicked for a statistic on what buttons were clicked the most?

**Comment by simon816** [comment]
exactly

**Comment by afroraydude** [comment]
Ok
